name: pypi_upload

on:
  push:
    branches: ["main"]

jobs:
  wheel_build_full:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: build wheels and sdist
        run: pipx run build

      - uses: actions/upload-artifact@v4
        with:
          path: ./dist/*

  upload_pypi:
    needs: [wheel_build_full]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.12
        with:
          skip_existing: true
          user: __token__
          password: ${{ secrets.PYPI_RELESO }}
